### ISSUE TITLE
Названия станций метро накладываются на сооружения метро

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all_cartostyle#28]
Названия станций не должны наезжать:
- друг на друга, 
- на иконки станций и выходов
- на платформы и подземные переходы станций.

![1](https://cloud.githubusercontent.com/assets/6493848/5523364/9eeac5fe-89d8-11e4-9223-dd858e07c3af.png)

**Comment by trolleway** [comment]
Так называемый рисёч
![demo1](https://cloud.githubusercontent.com/assets/4630662/5837590/82140a0a-a191-11e4-9eda-1cd2f09efe6b.png)
![demo2](https://cloud.githubusercontent.com/assets/4630662/5837591/84c83776-a191-11e4-9686-efda13ebe676.png)

**Comment by trolleway** [comment]
Сделал сдвиг названий станций метро от платформ на 10-16 зумах. В принципе это не идеально, можно дорабатывать ещё. Но сейчас платформы стало видно лучше на одиночных станциях.
