### ISSUE TITLE
В Амстердаме, Варшаве и Глазго нет иконок станций

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all_cartostyle#33]
Иконки станций на мелких зумах не показываются, зато показываются большие иконки выходов (там, где выходы отмечены)

![4](https://cloud.githubusercontent.com/assets/6493848/5523822/6e293382-89de-11e4-8fc2-d6410de885a7.png)

**Comment by trolleway** [comment]
Иконки добавлены
