### ISSUE TITLE
Добавить Лозанну

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all_cartostyle#35]

**Comment by trolleway** [comment]
![2015-01-23 13 41 32](https://cloud.githubusercontent.com/assets/4630662/5873265/95db7c60-a305-11e4-847d-38646ebc4dd2.png)
Пришлось добавить в скрипт импорта выкачивание Женевского озера, и изменить запросы в стиле, потому что там тегирование другое.
Местные осмеры линию m1 за метро не считают, теги station=subway на неё не ставят, поэтому станции её не рисуются.
